In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pickle
import csv

from gpu import set_gpu

import tensorflow as tf
from latent.ml.dl_subclass import MLP, MLPbeta, CNN, MLPprop, get_train
from latent.ml.dl_manual import nn_pass, conv
import latent.session_subclass as session
import latent.utils.data_utils as prd
from latent.ml.lda import train_lda, eval_lda

set_gpu()

Using TensorFlow backend.


Num GPUs Available:  1


In [2]:
data, params = prd.load_caps_train('traindata.mat')

In [3]:
ep = 30
n_dof = np.max(params[:,0])
    
# Train NNs
mlp = MLP(n_class=n_dof)
mlp_beta = MLPbeta(n_class=n_dof)
mlp_prop = MLPprop(n_class=n_dof)
cnn = CNN(n_class=n_dof)

optimizer = tf.keras.optimizers.Adam()
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.CategoricalAccuracy(name='train_accuracy')
train_prop_accuracy = tf.keras.metrics.MeanSquaredError(name='train_prop_accuracy')

# Train neural networks
models = [mlp, mlp_beta, cnn]
models = [cnn]

trainmlp, traincnn, y_train, x_train_mlp, x_train_cnn, x_train_lda, y_train_lda, x_train_aug, emg_scale, scaler, x_min, x_max, prop = prd.prep_train_caps(data, params)

for model in models:
    if isinstance(model,CNN):
        ds = traincnn
    else:
        ds = trainmlp
 
    prop_b = isinstance(model, MLPprop)
 
    train_mod = get_train(prop = prop_b)

    for epoch in range(ep):
        # Reset the metrics at the start of the next epoch
        train_loss.reset_states()
        train_accuracy.reset_states()

        for x, y, y2 in ds:
            if prop_b:
                train_mod(x, y, model, optimizer, train_loss, train_accuracy, train_prop_accuracy, y2)
            else:
                train_mod(x, y, model, optimizer, train_loss, train_accuracy)

        if epoch == 0 or epoch == ep-1:
            print(
                f'Epoch {epoch + 1}, '
                f'Loss: {train_loss.result():.2f}, '
                f'Accuracy: {train_accuracy.result() * 100:.2f}, '
                f'MSE: {train_prop_accuracy.result():.2f} '
            )
            
    del train_mod

# Train aligned LDA
# y_train_aug = np.argmax(y_train, axis=1)[...,np.newaxis]

# mlp_enc = mlp.get_layer(name='enc')
# w_mlp, c_mlp,_, _, _ = train_lda(mlp_enc(x_train_mlp).numpy(),y_train_aug)

# mlpbeta_enc = mlp_beta.get_layer(name='enc')
# w_mlpbeta, c_mlpbeta,_, _, _ = train_lda(mlpbeta_enc(x_train_mlp).numpy(),y_train_aug)

# cnn_enc = cnn.get_layer(name='enc')
# temp = cnn_enc(x_train_cnn[:x_train_cnn.shape[0]//2,...]).numpy()
# temp2 = np.vstack((temp,cnn_enc(x_train_cnn[x_train_cnn.shape[0]//2:,...]).numpy()))
# w_cnn, c_cnn,_, _, _ = train_lda(temp2,y_train_aug)

# # Train LDA
# w,c, _, _, _ = train_lda(x_train_lda,y_train_lda)
# w_aug,c_aug, _, _, _ = train_lda(x_train_aug,y_train_aug)

mlp_w = mlp.get_weights()
mlpb_w = mlp_beta.get_weights()
cnn_w = cnn.get_weights()
mlpp_w = mlp_prop.get_weights()

Epoch 1, Loss: 1.47, Accuracy: 47.26, MSE: 0.00 
Epoch 30, Loss: 0.10, Accuracy: 96.73, MSE: 0.00 


In [4]:
enc = cnn.get_layer(name='enc')

In [5]:
x = x_train_cnn[[0],...]
test = enc.conv1(x)
test2 = enc.conv2(test)
conv_w = enc.conv1.get_weights()
conv2_w = enc.conv2.get_weights()

In [56]:
conv_w[1][2]

0.06612824

In [78]:
conv_w[0][...,2].shape

(3, 3, 1)

In [73]:
np.squeeze(conv_w[0][...,2])

array([[-0.08940832,  0.09161861,  0.12015786],
       [ 0.18948266,  0.1187374 , -0.05035184],
       [-0.01214195, -0.00771844,  0.02403517]], dtype=float32)

In [72]:
padded[0:3,0:3]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.64598864, 0.6492197 ],
       [0.        , 0.04287094, 0.03051918]], dtype=float32)

In [9]:
np.squeeze(test[0,:,:,4])

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00687387],
       [0.0152956 , 0.        , 0.        , 0.        ],
       [0.08819538, 0.00199241, 0.        , 0.06424823],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]], dtype=float32)

In [12]:
np.squeeze(out[0,:,:,4])

array([[-0.        , -0.        , -0.        , -0.        ,  0.05034866],
       [-0.        , -0.        , -0.        ,  0.00687386,  0.05034866],
       [ 0.01529561, -0.        , -0.        , -0.        ,  0.05034866],
       [ 0.08819538,  0.00199241, -0.        ,  0.06424822,  0.05034866],
       [-0.        , -0.        , -0.        , -0.        ,  0.05034866],
       [-0.        , -0.        , -0.        , -0.        ,  0.05034866]])

In [11]:
out = conv(x,conv_w,k = (3,2),stride=1)

In [20]:
out2 = conv(out,conv2_w,stride=2)

In [6]:
# Save neural network architectures into csv
arch = ['RELU1','BN1','RELU2','BN2','RELU3','BN3','DEN','BN4','SOFTMAX','PROP']
w = {}
w_in = mlpp_w
folder = 'weights_p'
path = 'python/'

i = 0
for l in arch:
    w_layer = []
    if 'BN' in l:
        w_layer = np.vstack((np.vstack((np.vstack((w_in[i],w_in[i+1])),w_in[i+2])),w_in[i+3]))
        i += 4
    else:
        w_layer = np.vstack((w_in[i],w_in[i+1]))
        i += 2
    
    # Save to current folder
    with open(path + folder + '/' + l + '.csv', 'w', newline='') as f:
        writer = csv.writer(f)
        # write multiple rows
        writer.writerows(w_layer)

    # Save to embedded
    try:
        with open('//192.168.20.2/config/modes/caps/upper_limb/dl_ctrl/DATA/' + folder + '/'  + l + '.csv', 'w', newline='') as f:
            writer = csv.writer(f)
            # write multiple rows
            writer.writerows(w_layer)
    except:
        print('no embedded')
    w[l] = w_layer

fill = len(emg_scale) - len(x_min)
temp = np.hstack((np.vstack((x_min[...,np.newaxis],np.zeros((fill,1)))), np.vstack((x_max[...,np.newaxis],np.zeros((fill,1))))))
scales = np.hstack((emg_scale,temp))

# Save to current folder
with open(path + folder + '/ARCH.csv', 'w', newline='') as f:
        writer = csv.writer(f,delimiter=',')
        # write multiple rows
        for i in arch:
            writer.writerow([i])

with open(path + folder + '/scales.csv', 'w', newline='') as f:
        writer = csv.writer(f)
        # write multiple rows
        writer.writerows(scales)

# Save to embedded
try:
    with open('//192.168.20.2/config/modes/caps/upper_limb/dl_ctrl/DATA/' + folder + '/ARCH.csv', 'w', newline='') as f:
            writer = csv.writer(f,delimiter=',')
            # write multiple rows
            for i in arch:
                writer.writerow([i])

    with open('//192.168.20.2/config/modes/caps/upper_limb/dl_ctrl/DATA/' + folder + '/scales.csv', 'w', newline='') as f:
            writer = csv.writer(f)
            # write multiple rows
            writer.writerows(scales)
except:
    print('no embedded')

no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
no embedded
